apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: SoftwareTemplate
  title: This is a software template
  description: An Example Software  Template
  efficiency-boost:
    value: 30
    unit: minutes
    impact: "Turbocharges development by eliminating software setup"
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

  output:
    links:
      - title: NAME
        url: ${{ steps.parameters.name}}